from typing import Annotated, Sequence
from datetime import date, timedelta, datetime
from typing_extensions import TypedDict, Optional
from langchain_openai import ChatOpenAI
from tradingagents.agents import *
from langgraph.prebuilt import ToolNode
from langgraph.graph import END, StateGraph, START, MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    risky_history: Annotated[
        str, "Risky Agent's Conversation history"
    ]  # Conversation history
    safe_history: Annotated[
        str, "Safe Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_risky_response: Annotated[
        str, "Latest response by the risky analyst"
    ]  # Last response
    current_safe_response: Annotated[
        str, "Latest response by the safe analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]
    research_summary: Annotated[
        str,
        "Compressed summary of market, news, fundamentals, and sentiment reports for downstream quantitative agents.",
    ]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    # quantitative research and strategy step
    factors_spec: Annotated[
        str,
        "Natural-language specification or hypothesis description of quantitative factors and signals used for strategy design",
    ]
    factor_values: Annotated[
        str,
        "JSON string describing factor DEFINITIONS / code (e.g. formulas, code snippets, or DSL specs) that downstream agents can embed into controllers; not raw time-series values.",
    ]
    strategy_template: Annotated[
        str,
        "Selected controller template or schema used as the base for strategy configuration",
    ]
    strategy_config: Annotated[
        str,
        "Concrete strategy configuration (typically a JSON string) that can be sent to the backtesting engine",
    ]
    backtest_results: Annotated[
        str,
        "Backtesting results including key metrics such as Sharpe ratio, max drawdown, and PnL curves",
    ]
    selected_strategy_summary: Annotated[
        str,
        "Natural language summary of the selected strategy and its backtest performance",
    ]
    strategy_acceptable: Annotated[
        bool,
        "Whether the current strategy and backtest performance meet the predefined acceptance criteria",
    ]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    risk_control_plan: Annotated[
        str,
        "Structured risk control suggestions from the quantitative Risk Manager (markdown / text).",
    ]
    risk_decision: Annotated[
        str,
        "Final risk decision label from Risk Manager, e.g. ACCEPT/ADJUST/REJECT.",
    ]
    risk_adjustment_pass: Annotated[
        bool,
        "Whether a risk-driven strategy adjustment pass has already been performed.",
    ]
